config/routes.rb
Rails.application.routes.draw do
  resources :railway_stations
  resources :trains

  get 'welcome/index' # т.е. он теперь умеет отвечать на такой запрос

  root "welcome#index" # страница по умолчанию

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord

  validates :title, presence: true

end

app/models/train.rb
class Train < ApplicationRecord

  validates :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/railway_stations_controller.rb
class RailwayStationsController < ApplicationController
  before_action :set_railway_station, only: %i[ show edit update destroy ]

  def index
    @railway_stations = RailwayStation.all
  end

  def show
  end

  def new
    @railway_station = RailwayStation.new
  end

  def create
    @railway_station = RailwayStation.new(railway_station_params)

    respond_to do |format|
      if @railway_station.save
        format.html { redirect_to railway_station_url(@railway_station), notice: "Станция успешно создана." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @railway_station.update(railway_station_params)
        format.html { redirect_to railway_station_url(@railway_station), notice: "Станция успешно изменена." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @railway_station.destroy

    respond_to do |format|
      format.html { redirect_to railway_stations_url, notice: "Станция успешно удалена." }
    end
  end

  private

    def set_railway_station
      @railway_station = RailwayStation.find(params[:id])
    end

    def railway_station_params
      params.require(:railway_station).permit(:title)
    end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: %i[ show edit update destroy ]

  def index
    @trains = Train.all
  end

  def show
  end

  def new
    @train = Train.new
  end

  def create
    @train = Train.new(train_params)

    respond_to do |format|
      if @train.save
        format.html { redirect_to train_url(@train), notice: "Поезд успешно создан." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to train_url(@train), notice: "Поезд успешно изменен." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @train.destroy

    respond_to do |format|
      format.html { redirect_to trains_url, notice: "Поезд успешно удален." }
    end
  end
  
  private

  def set_train
    @train = Train.find(params[:id])
  end

  def train_params
    params.require(:train).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/railway_stations/_form.html.erb
<%= form_with(model: railway_station) do |form| %>
  <% if railway_station.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(railway_station.errors.count, "error") %> не удалось сохранить:</h2>

      <ul>
        <% railway_station.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit "Ok" %>
  </div>
<% end %>

app/views/railway_stations/_railway_station.html.erb
<div id="<%= dom_id railway_station %>">
  <p>
    <%# <strong>Название:</strong> %>
    <%#= railway_station.title %>
    <%= link_to railway_station.title , railway_station %>
  </p>

</div>

app/views/railway_stations/edit.html.erb
<h1>Редактировать</h1>

<%= render "form", railway_station: @railway_station %>

<br>

<div>
  <%= link_to "Назад", @railway_station %> |
  <%= link_to "Вернуться к списку станций", railway_stations_path %>
</div>

app/views/railway_stations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Список станций</h1>

<div id="railway_stations">
  <% @railway_stations.each do |railway_station| %>
    <ul>
      <li><%= render railway_station %></li>
    </ul>
  <% end %>
</div>

  <p>_________________________</p>

  <%= link_to "Создать новую станцию", new_railway_station_path %>

  <br>

  <%= link_to "На главную", welcome_index_path %>

app/views/railway_stations/new.html.erb
<h1>Создать новую станцию</h1>

<%= render "form", railway_station: @railway_station %>

<br>

<div>
  <%= link_to "Назад", railway_stations_path %>
</div>

app/views/railway_stations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @railway_station %>

<div>
  <%= link_to "Изменить", edit_railway_station_path(@railway_station) %> |
  <%= link_to "Список станций", railway_stations_path %>

  <%= button_to "Удалить", @railway_station, method: :delete %>
</div>

app/views/trains/_form.html.erb
<%= form_with(model: train) do |form| %>
  <% if train.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(train.errors.count, "error") %> не удалось сохранить:</h2>

      <ul>
        <% train.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit "Ok" %>
  </div>
<% end %>

app/views/trains/_train.html.erb
<div id="<%= dom_id train %>">
  <p>
    <%= link_to train.name , train %>
  </p>

</div>

app/views/trains/edit.html.erb
<h1>Редактировать</h1>

<%= render "form", train: @train %>

<br>

<div>
  <%= link_to "Назад", @train %> |
  <%= link_to "Вернуться к списку поездов", trains_path %>
</div>

app/views/trains/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Список поездов</h1>

<div id="trains">
  <% @trains.each do |train| %>
    <ul>
      <li><%= render train %></li>
    </ul>
  <% end %>
</div>

  <p>_________________________</p>

  <%= link_to "Создать новый поезд", new_train_path %>

  <br>

  <%= link_to "На главную", welcome_index_path %>

app/views/trains/new.html.erb
<h1>Создать новый поезд</h1>

<%= render "form", train: @train %>

<br>

<div>
  <%= link_to "Назад", trains_path %>
</div>

app/views/trains/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @train %>

<div>
  <%= link_to "Изменить", edit_train_path(@train) %> |
  <%= link_to "Список поездов", trains_path %>

  <%= button_to "Удалить", @train, method: :delete %>
</div>

app/views/welcome/index.html.erb
<h1>Привет, это снова ты =)</h1>

<p>Ну тут уже пошел сайт...</p>

<p><%= link_to "Список станций", railway_stations_path %></p>

<p><%= link_to "Список поездов", trains_path %></p>